name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: docker://firedrakeproject/firedrake-vanilla-default:2026.4.1
      options: --user root

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Python info
        shell: bash
        run: |
          which python3
          python3 -c "import sys; print('\n'.join(sys.path))"
          python3 -c "from firedrake import *"

      - name: Install dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python3 -m pip install pytest-cov
          python3 -m pip install pytest-check
          python3 -m pip install coveralls

      - name: Install firedrake-ts
        shell: bash
        run: |
          python3 -m pip install -e .

      - name: Test with pytest
        shell: bash
        run: |
          python3 -c "import sys; print('\n'.join(sys.path))"
          python3 -m pytest --cov=firedrake_ts --cov-config=tests/.coveragerc --cov-report=xml tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false

      - name: Coveralls
        uses: coverallsapp/github-action@v2
